# Generated by Django 2.0.5 on 2018-05-09 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linguagem_nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_date', models.DateTimeField(verbose_name='data do search')),
                ('linguagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srchdstk.Linguagem')),
            ],
        ),
    ]
